services:
  app:
    build: 
      context: ./tb
    container_name: tb_python
    volumes:
      - ./tb/app:/app # Map app directory to /app in container
      - ./tb/image:/image
      - ./tb/dataset:/dataset
      - ./tb/yolo_output:/yolo_output
    ports:
      - "8000:8000" 
    command: >
      bash -c "python run.py"